@url_dev=http://localhost:3055/v1/api

### create product
POST {{url_dev}}/products/
Content-Type: application/json
x-api-key: 901ad9efc6f626c3962a06bccb0311a98aabac0bd42cd000e0c29d64c257348721d412dd28ffe281525915e92f596670681193c32076cd0dd7f0427e6cd0300c
x-client-id: 66d1bea3afc997054e986917
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQxYmVhM2FmYzk5NzA1NGU5ODY5MTciLCJlbWFpbCI6ImpvaG5kb2UrMUBnbWFpbC5jb20iLCJpYXQiOjE3MjUwNDcyOTksImV4cCI6MTcyNTIyMDA5OX0.OZ07W7h6dEmnRQCT3ZESsYNTnpcZ1F3kzXDNiXaMbuQ

{
  "name": "Samsung Galaxy S21",
  "thumb": "https://example.com/samsung-galaxy-s21-thumb.jpg",
  "description": "Latest Samsung flagship smartphone with advanced features.",
  "price": 799.99,
  "quantity": 50,
  "type": "Electronic",
  "attributes": {
    "manufacturer": "Samsung",
    "model": "Galaxy S21",
    "color": "Phantom Gray"
  }
}